import { readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { GLOSSARY_TOPICS } from "@/lib/constants";
import { parseGlossaryCsv } from "@/lib/import/glossary-csv";
import { collapseSynonyms } from "@/lib/import/synonyms";
import { extractFigureImage, type GlossaryFigure } from "@/lib/import/glossary-images";

// Scrapes each glossary term's SLB page for its figure and emits a SQL backfill that
// hotlinks the image into questions.metadata. Keys terms the same way the DB does
// (collapsed canonical rows), and caches results so re-runs are cheap/resumable.
const CONCURRENCY = 8;
const REQUEST_TIMEOUT_MS = 15_000;
const CACHE_PATH = path.join(process.cwd(), "data", "glossary-images.json");
const SQL_PATH = path.join(process.cwd(), "supabase", "migrations", "0008_glossary_images.sql");

type WorkItem = { topicName: string; answer: string; url: string };
type Cache = Record<string, GlossaryFigure | null>;

function sqlQuote(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

async function loadCache(): Promise<Cache> {
  if (!existsSync(CACHE_PATH)) {
    return {};
  }
  return JSON.parse(await readFile(CACHE_PATH, "utf8")) as Cache;
}

async function fetchFigure(url: string): Promise<GlossaryFigure | null> {
  for (let attempt = 0; attempt < 2; attempt += 1) {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);
    try {
      const res = await fetch(url, {
        headers: { "user-agent": "Mozilla/5.0 (petrobowl-trainer glossary image scraper)" },
        signal: controller.signal
      });
      if (!res.ok) {
        if (attempt > 0) return null;
        continue;
      }
      return extractFigureImage(await res.text());
    } catch {
      if (attempt > 0) return null;
    } finally {
      clearTimeout(timer);
    }
  }
  return null;
}

async function runPool<T>(items: T[], limit: number, worker: (item: T, index: number) => Promise<void>) {
  let index = 0;
  const runners = Array.from({ length: Math.min(limit, items.length) }, async () => {
    while (index < items.length) {
      const current = index;
      index += 1;
      await worker(items[current], current);
    }
  });
  await Promise.all(runners);
}

async function buildWorklist(): Promise<WorkItem[]> {
  const dir = path.join(process.cwd(), "data", "slb_glossary");
  const items: WorkItem[] = [];
  for (const { slug, name } of GLOSSARY_TOPICS) {
    const content = await readFile(path.join(dir, `${slug}.csv`), "utf8");
    const topic = collapseSynonyms(parseGlossaryCsv(slug, name, content));
    for (const question of topic.questions) {
      if (question.metadata.url) {
        items.push({ topicName: name, answer: question.answer, url: question.metadata.url });
      }
    }
  }
  return items;
}

function generateSql(worklist: WorkItem[], cache: Cache): { sql: string; withImage: number } {
  const lines = [
    "-- Hotlink SLB glossary figures into questions.metadata (imageUrl/imageCaption).",
    "-- Generated by scripts/scrape-glossary-images.ts. Idempotent; safe to re-run.",
    "-- Images are served from glossary.slb.com (SLB copyright) — internal team use.",
    "",
    "begin;"
  ];
  let withImage = 0;
  let currentTopic = "";

  for (const item of worklist) {
    const figure = cache[item.url];
    if (!figure) {
      continue;
    }
    withImage += 1;
    if (item.topicName !== currentTopic) {
      lines.push(`-- ${item.topicName}`);
      currentTopic = item.topicName;
    }
    const payload = figure.caption
      ? `jsonb_build_object('imageUrl', ${sqlQuote(figure.url)}, 'imageCaption', ${sqlQuote(figure.caption)})`
      : `jsonb_build_object('imageUrl', ${sqlQuote(figure.url)})`;
    const topicPredicate =
      `topic_id in (select id from public.topics ` +
      `where name = ${sqlQuote(item.topicName)} and source = 'SLB Glossary' and retired_at is null)`;
    lines.push(
      `update public.questions set metadata = coalesce(metadata, '{}'::jsonb) || ${payload} ` +
        `where ${topicPredicate} and answer = ${sqlQuote(item.answer)};`
    );
  }

  lines.push("", "commit;", "");
  return { sql: lines.join("\n"), withImage };
}

async function main() {
  const worklist = await buildWorklist();
  const uniqueUrls = [...new Set(worklist.map((item) => item.url))];
  const cache = await loadCache();
  const pending = uniqueUrls.filter((url) => !(url in cache));

  console.log(`${worklist.length} terms, ${uniqueUrls.length} unique URLs, ${pending.length} to fetch.`);

  let done = 0;
  await runPool(pending, CONCURRENCY, async (url) => {
    cache[url] = await fetchFigure(url);
    done += 1;
    if (done % 200 === 0) {
      await writeFile(CACHE_PATH, JSON.stringify(cache), "utf8");
      console.log(`  ...${done}/${pending.length} fetched`);
    }
  });

  await writeFile(CACHE_PATH, JSON.stringify(cache, null, 0), "utf8");

  const { sql, withImage } = generateSql(worklist, cache);
  await writeFile(SQL_PATH, sql, "utf8");

  const hits = uniqueUrls.filter((url) => cache[url]).length;
  console.log(
    `Done. ${hits}/${uniqueUrls.length} pages have a figure ` +
      `(${Math.round((hits / uniqueUrls.length) * 100)}%). ${withImage} term rows will get an image.`
  );
  console.log(`Wrote ${SQL_PATH}`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
